### ISSUE TITLE
[Shortcode Editor] Limit post types and shortcodes

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson-PageBuilder-Extension#21]
There is a problem of usability that I think will force us to re think how the shortcode editor works. 
I think we need to build an option in the Page Builder like this: 

http://joxi.ru/VrweWGyH7PJL2X

We need two things:
1. To be able to enable only the editor shortcodes for posts
2. A config file that will let us select what shortcodes we'll have in the editor shortcodes. Considering that we can't use columns that are shortcodes that are not meant to be used in full width, so we'll need the possibility ro remove those.

**Comment by ierpe** [comment]
Hi,
As a similar enhancement, I had thought that we could have a "Widgets" tab in the page builder, where you could just call the widgets into the page/posts content, in a similar fashion of the Site Origin page builder.

You could have an option to enable / disable this tab in the same way you are suggesting here.

What do you think?

**Comment by DimiBaitanciuc** [comment]
We already have a widget shortcode - http://joxi.ru/8AnN51aiz6XGAO that lets up add any widget on the page. Is this what you mean ? or I am missing something ? 

(I'm not familiar with Site Origin page builder)

**Comment by ierpe** [comment]
Yes I know that, but in the end it's not very handy, because you need to make a widget sidebar, then fill it with widgets, then that's what you can add from the page builder. So it is handy to manage widget "groups", but what if you just want to add a single Widget in a page or a post with page builder. You have to first create a Widget area...

What I mean is to add a single widget, and have the Wigdet form (if the widget has one) directly in the builder, know what I mean?

**Comment by andreiglingeanu** [comment]
I may be able to implement this for https://github.com/ThemeFuse/Unyson-WP-Shortcodes-Extension. Is this any good?
