### ISSUE TITLE
can see page content in page builder, but default editor is empty

### ISSUE THREAD

**Issue by moldcraft** [ThemeFuse/Unyson-PageBuilder-Extension#31]
> https://wordpress.org/support/topic/can-see-page-content-in-page-builder-but-default-editor-is-empty

**Webprom Design**

After inserting page text content into section and full width column with page builder, can't see the raw page code in default editor. Should it be so?

----

**Unyson**

Just to clarify the steps to reproduce this:

* Open "Add new page"
* Write some text in default editor
* Press the "Visual Page Builder" button
* Press post "Update" button
* Switch back to Default editor (the content is empty)

Those are right?

----

**Webprom Design**

yes, after editing in your editor when switching to default editor, visual and text mode, they are empty. But your editor shows all things I've added.

All latest versions with underscores theme http://underscores.me/

----

**Unyson**

Yes, this is the correct behavior.

In case you have a lot of shortcodes/elements in builder, then you switch to default editor, what do you expect to see, a very big text `[shortcode_1][shortcode_2][shortcode_6778][shortcode_whatever]...[/shortcode_1]` ?

----

**Webprom Design**

yes, or anything, currently it's blank and empty

in case I'll need to adjust some code, need to use a regular editor, and there is a fear of what will happen if i disable visual builder...
or if I'll need to copy some code to another page...

**Comment by webprom** [comment]
is it my local problem or was it built this way?

**Comment by moldcraft** [comment]
it's built this way.

We decided that the user doesn't need to see that big shortcodes string

```
[section is_fullwidth="1" background_color="" background_image="{&quot;type&quot;:&quot;custom&quot;,&quot;custom&quot;:&quot;&quot;,&quot;predefined&quot;:&quot;&quot;,&quot;data&quot;:{&quot;icon&quot;:&quot;&quot;,&quot;css&quot;:&#91;&#93;}}" video="https://www.youtube.com/watch?v=LjCzPp-MK48" auto_generated="" first_in_builder="1" _array_keys="{&quot;background_image&quot;:&quot;background_image&quot;}" _made_with_builder="true"][row][column width="1_1" _made_with_builder="true"][button label="Hi" link="#" target="_blank" color="" _made_with_builder="true"][/button][/column][/row][row][column width="1_1" _made_with_builder="true"][button label="Hi" link="#" target="_blank" color="" _made_with_builder="true"][/button][/column][/row][row][column width="1_1" _made_with_builder="true"][button label="Hi" link="#" target="_blank" color="" _made_with_builder="true"][/button][/column][/row][row][column width="1_1" _made_with_builder="true"][button label="Hi" link="#" target="_blank" color="" _made_with_builder="true"][/button][/column][/row][/section][section is_fullwidth="" background_color="#d6b7b7" background_image="{&quot;type&quot;:&quot;custom&quot;,&quot;custom&quot;:&quot;&quot;,&quot;predefined&quot;:&quot;&quot;,&quot;data&quot;:{&quot;icon&quot;:&quot;&quot;,&quot;css&quot;:&#91;&#93;}}" video="" auto_generated="" _array_keys="{&quot;background_image&quot;:&quot;background_image&quot;}" _made_with_builder="true"][row][column width="1_1" _made_with_builder="true"][button label="Hi" link="#" target="_blank" color="" _made_with_builder="true"][/button][/column][/row][row][column width="1_1" _made_with_builder="true"][button label="Hi" link="#" target="_blank" color="" _made_with_builder="true"][/button][/column][/row][row][column width="1_1" _made_with_builder="true"][button label="Hi" link="#" target="_blank" color="" _made_with_builder="true"][/button][/column][/row][row][column width="1_1" _made_with_builder="true"][button label="Hi" link="#" target="_blank" color="" _made_with_builder="true"][/button][/column][/row][/section]
```

it will use Visual Builder or will move to Default editor to start a new text only content.

----

We will come back with a final reply soon. (If we will leave that behavior or will make some changes)

**Comment by webprom** [comment]
i see, if you decide to leave it as before, maybe disable default editor button

**Comment by moldcraft** [comment]
> maybe disable default editor button

I don't think this is a good idea.
For e.g. user just installed Unyson, then he press Visual Builder button on an existing page (with finished content) then want to switch back.

**Comment by webprom** [comment]
i've tried several other visual builders, and all of them have also default editors populated... empty default editor looks scary

**Comment by llemurya** [comment]
@webprom It is a normal workflow, because when you click on Default Editor Button, you want to add a simple text or description and the steps to do this are :
1. Delete all content that contains shortcodes
2. Insert your text
We decide to simplify the steps, what is why you see the default editor empty, and in our opinion the editor with shortcodes looks scarier than an empty editor.
`
[section is_fullwidth="" background_color="" background_image="" video="" auto_generated="1" _made_with_builder="true"][row][column width="3_4" demo_text="" demo_select="" _made_with_builder="true"][/column][/row][row][column width="2_3" demo_text="" demo_select="" _made_with_builder="true"][/column][column width="1_5" demo_text="" demo_select="" _made_with_builder="true"][/column][/row][row][column width="1_4" demo_text="" demo_select="" _made_with_builder="true"][/column][column width="1_2" demo_text="" demo_select="" _made_with_builder="true"][/column][/row][row][column width="1_1" demo_text="" demo_select="" _made_with_builder="true"][/column][/row][row][column width="1_4" demo_text="" demo_select="" _made_with_builder="true"][/column][column width="1_5" demo_text="" demo_select="" _made_with_builder="true"][/column][column width="1_6" demo_text="" demo_select="" _made_with_builder="true"][/column][/row][/section]
` 

If the user wants to delete the shortcode it can make from the visual part of the builder. It is more safe for user , because if user accidentally will delete incorrect the shortcode tag, the whole builder will work wrong, it is not so good for user experience.
