### ISSUE TITLE
Installing this PLugin via FTP

### ISSUE THREAD

**Issue by ryangreg55** [ThemeFuse/Unyson-PageBuilder-Extension#37]
I am having issues adding this via FTP as I do not know how. I need to install this Pagebuilder and Portfolio however I cannot due to my hosting. 

Can anyone give me a guide to installing this as it would be much appreciated. Or if there is a developer here who can set these up for me at a price, please let me know. 

Alternatively, would changing hosting provider allow me to install these extensions?

Kind regards,
Ryan

**Comment by moldcraft** [comment]
Hi,

Anyway you will need to update extensions at some point (because we constantly release bug fixes and new features). So better to fix the problem with your hosting instead of uploading extensions manually.

Please ask the current hosting to allow requests to http://github-api-cache.unyson.io/ (this site is used for extensions update) or change the hosting provider.
